
name: Provision Lab

on:
  # Run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      EmailAddress:
        description: 'Enter your Email Address'
        default: ''
        required: true

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
    - name: User Operation Request
      id: userOp
      uses: fjogeleit/http-request-action@v1
      with:
        url: https://f1dcf3d2-d4e7-45f4-ac93-5394986d1fb4.webhook.eus.azure-automation.net/webhooks?token=alY0%2bX8%2fv%2fYrFP65PU0psQrwPoYWsTKIBdQgx9bF5v4%3d
        method: 'POST'
        customHeaders: '{"Content-Type": "application/json"}'
        data: '{"userop": "Create", "username": "","odlconfigname": "sdwan-lab", "email": "${{ github.event.inputs.EmailAddress }}"}'

    - name: User Operation Response
      run: |
        echo ${{ steps.userOp.outputs.response }}
        echo ${{ steps.userOp.outputs.headers }}
        echo ${{ fromJson(steps.userOp.outputs.response).JobIds }}